version: '3.5'

services:
  adonis_js:
    build: ./
    environment:
      - NODE_ENV=${NODE_ENV}
    working_dir: /sakila_graphQl
    volumes:
      - ./:/sakila_graphQl
    ports:
      - 3333:${PORT}
    links:
      - "mysql_db"
    command: bash -c "npm install && npm run start"
    networks:
      - sakila_network

  mysql_db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - sakila_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - 3306:${DB_PORT}
    networks:
      - sakila_network

volumes:
  sakila_db_data:

networks:
  sakila_network:
